AllCops:
  DisplayCopNames: truew

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/Copyright:
  Enabled: true
  Notice: '# Copyright \(c\) 2016 Nathan Baum'
  AutocorrectNotice: '# Copyright (c) 2016 Nathan Baum'

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/Encoding:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/SpaceAfterMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
