default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: aurora/dev

test:
  <<: *default
  database: aurora/test

production:
  <<: *default
  database: aurora/live
